name: medkitapp
description: An app for common people to help them know about different diseases/symptoms and there medications.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^4.0.2
  page_transition: ^2.0.5
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.2
  toast: ^0.2.9
  google_sign_in: ^5.3.0
  url_launcher: ^6.1.0
  location: ^4.3.0
  provider: ^6.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  fluttertoast: ^8.0.9 
  uuid: 3.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/
