// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuGOvqKHaht5cqn5jCHcstn0oktRUS8Jk',
    appId: '1:825575090121:web:3ed93e6a50d3675ecbaa18',
    messagingSenderId: '825575090121',
    projectId: 'medk-4d6c9',
    authDomain: 'medk-4d6c9.firebaseapp.com',
    storageBucket: 'medk-4d6c9.appspot.com',
    measurementId: 'G-59W39TH4R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2zT2YTSRuHEDuO7JuyseKH2YFQsnl6tI',
    appId: '1:825575090121:android:777a6a02e8099018cbaa18',
    messagingSenderId: '825575090121',
    projectId: 'medk-4d6c9',
    storageBucket: 'medk-4d6c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8sSf4QlF1n6r2y3RuFB4cmp_puCFqd0',
    appId: '1:825575090121:ios:7e635e0e36080855cbaa18',
    messagingSenderId: '825575090121',
    projectId: 'medk-4d6c9',
    storageBucket: 'medk-4d6c9.appspot.com',
    iosClientId: '825575090121-7uv9lbracbs78289u5i417rdkg9iom9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.medkit',
  );
}
